### ISSUE TITLE
Code meaning

### ISSUE THREAD

**Issue by wangxinyue11** [Herosan163/AgeEstimation#2]
Can you explain to me what this sentence means? Thank you.
self.labels.append(int(basename[4:6]))
Is it to get the age label of FGNET?and When I run in morph2, how should I get the label?

**Comment by wangxinyue11** [comment]
Is it to get the age label of FGNET?

**Comment by Herosan163** [comment]
An image filename contains age label in FGNET, e.g., "001A02.JPG". The code gets the age from 4th to 5th in the filename. 
Sorry, I don't know about morph2.
