### ISSUE TITLE
LAMBDA_1 and LAMBDA_2 switched?

### ISSUE THREAD

**Issue by maxmarketit** [Herosan163/AgeEstimation#5]
in `main.py`

```
criterion1 = MeanVarianceLoss(LAMBDA_2, LAMBDA_1, START_AGE, END_AGE).cuda()
```

it looks like `LAMBDA_2` and `LAMBDA_1` are switched.

anyhow I couldn't replicate your result so it might be because of the above. I am not sure.

I had to go through 1000+ epochs to reach MAE of 3 or 4.

**Comment by Herosan163** [comment]
Thank you for your pointing out. I fixed this bug and uploaded new result.
